package StockExchangeService;


/**
* StockExchangeService/_ServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockExchangeService.idl
* Thursday, June 3, 2021 11:53:15 AM CEST
*/

public class _ServiceStub extends org.omg.CORBA.portable.ObjectImpl implements StockExchangeService.Service
{

  public String[] getAvailableStockExchanges ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAvailableStockExchanges", true);
                $in = _invoke ($out);
                String $result[] = StockExchangeService.ServicePackage.stringSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAvailableStockExchanges (        );
            } finally {
                _releaseReply ($in);
            }
  } // getAvailableStockExchanges

  public StockExchangeService.StockPrice getLastQuotation (String ticker, String stockExchange)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLastQuotation", true);
                $out.write_string (ticker);
                $out.write_string (stockExchange);
                $in = _invoke ($out);
                StockExchangeService.StockPrice $result = StockExchangeService.StockPriceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLastQuotation (ticker, stockExchange        );
            } finally {
                _releaseReply ($in);
            }
  } // getLastQuotation

  public boolean addNewQuotation (StockExchangeService.StockPrice stockPrice, String stockExchange)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addNewQuotation", true);
                StockExchangeService.StockPriceHelper.write ($out, stockPrice);
                $out.write_string (stockExchange);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addNewQuotation (stockPrice, stockExchange        );
            } finally {
                _releaseReply ($in);
            }
  } // addNewQuotation

  public boolean addNewStockExchange (String stockExchange)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addNewStockExchange", true);
                $out.write_string (stockExchange);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addNewStockExchange (stockExchange        );
            } finally {
                _releaseReply ($in);
            }
  } // addNewStockExchange

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StockExchangeService/Service:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServiceStub
