package StockExchangeService;


/**
* StockExchangeService/Service.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockExchangeService.idl
* Thursday, June 3, 2021 2:29:03 PM CEST
*/

public interface Service extends ServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Service
