package StockExchangeService;


/**
* StockExchangeService/ServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockExchangeService.idl
* Thursday, June 3, 2021 2:29:03 PM CEST
*/

public interface ServiceOperations 
{
  String getAvailableStockExchanges ();
  StockExchangeService.StockPrice getLastQuotationByTickerAndStockExchange (String ticker, String stockExchange);
  boolean addNewQuotation (StockExchangeService.StockPrice stockPrice, String stockExchange);
  boolean addNewStockExchange (String stockExchange);
} // interface ServiceOperations
