package StockExchangeService;


/**
* StockExchangeService/ServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockExchangeService.idl
* Thursday, June 3, 2021 11:53:15 AM CEST
*/

public interface ServiceOperations 
{
  String[] getAvailableStockExchanges ();
  StockExchangeService.StockPrice getLastQuotation (String ticker, String stockExchange);
  boolean addNewQuotation (StockExchangeService.StockPrice stockPrice, String stockExchange);
  boolean addNewStockExchange (String stockExchange);
} // interface ServiceOperations
