package StockExchangeService;


/**
* StockExchangeService/StockPriceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockExchangeService.idl
* Thursday, June 3, 2021 2:18:38 PM CEST
*/

public interface StockPriceOperations 
{
  String ticker ();
  void ticker (String newTicker);
  double price ();
  void price (double newPrice);
  String currency ();
  void currency (String newCurrency);
  int measurementDateTime ();
  void measurementDateTime (int newMeasurementDateTime);
  String stockExchange ();
  void stockExchange (String newStockExchange);
} // interface StockPriceOperations
