package StockExchangeService;


/**
* StockExchangeService/StockPrice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockExchangeService.idl
* Thursday, June 3, 2021 2:29:03 PM CEST
*/

public interface StockPrice extends StockPriceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StockPrice
