package StockExchangeService.ServicePackage;


/**
* StockExchangeService/ServicePackage/stockPriceDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockExchangeService.idl
* Thursday, June 3, 2021 2:18:38 PM CEST
*/

public final class stockPriceDataHolder implements org.omg.CORBA.portable.Streamable
{
  public StockExchangeService.StockPrice value[] = null;

  public stockPriceDataHolder ()
  {
  }

  public stockPriceDataHolder (StockExchangeService.StockPrice[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StockExchangeService.ServicePackage.stockPriceDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StockExchangeService.ServicePackage.stockPriceDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockExchangeService.ServicePackage.stockPriceDataHelper.type ();
  }

}
