package StockExchangeService.ServicePackage;


/**
* StockExchangeService/ServicePackage/stringSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockExchangeService.idl
* Thursday, June 3, 2021 11:53:15 AM CEST
*/

public final class stringSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public stringSequenceHolder ()
  {
  }

  public stringSequenceHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StockExchangeService.ServicePackage.stringSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StockExchangeService.ServicePackage.stringSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockExchangeService.ServicePackage.stringSequenceHelper.type ();
  }

}
